language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
# command to run tests
script:
  - py -3.6 -m unittest discover -s test -p "test_*.py"
  - coverage run script/discover.py
after_success:
  - codecov